version: "3.8"

services:
  postgresDB:
    image: postgres:15-alpine
    container_name: user-management-db
    environment:
      POSTGRES_USER: akibaz
      POSTGRES_PASSWORD: akibaz123
      POSTGRES_DB: user_management
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - user-management-network
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U akibaz" ]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: user-management-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@akibaz.dev
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - user-management-network
    restart: unless-stopped
    depends_on:
      - postgresDB

volumes:
  postgres_data:
    driver: local
  pgadmin_data:
    driver: local

networks:
  user-management-network:
    driver: bridge
